name: rnachrom-test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.10=hd590300_0
  - bedtools=2.31.0=hf5e1c6e_3
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.20.1=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - expat=2.5.0=hcb278e6_1
  - fastuniq=1.1=h470a237_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - graphite2=1.3.13=h58526e2_1001
  - harfbuzz=8.2.1=h3d44ed6_0
  - hisat2=2.2.1=hdbdd923_6
  - htslib=1.18=h81da01d_0
  - icu=73.2=h59595ed_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - lcms2=2.15=hb7c19ff_3
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.4.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libglib=2.78.0=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_2
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.1=hd590300_0
  - libpng=1.6.39=h753d276_0
  - libsqlite=3.43.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtiff=4.6.0=ha9c0a0a_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - openjdk=21.0.0=haa376d0_0
  - openssl=3.1.3=hd590300_0
  - pcre2=10.40=hc3806b6_0
  - perl=5.32.1=4_hd590300_perl5
  - pip=23.3=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.9.18=h0755675_0_cpython
  - readline=8.2=h8228510_1
  - samtools=1.18=h50ea8bc_1
  - seqtk=1.4=he4a0461_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - stringtie=2.2.1=h6b7c446_4
  - tk=8.6.13=h2797004_0
  - trimmomatic=0.39=hdfd78af_2
  - tzdata=2023c=h71feb2d_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
